<?php if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) die();
?>

<? $APPLICATION->IncludeComponent(
	"citrus.forms:iblock.element", 
	"simple", 
	array(
		"AFTER_FORM_TOOLTIP" => "",
		"ANCHOR_ID" => "",
		"BEFORE_FORM_TOOLTIP" => "",
		"BUTTON_POSITION" => "CENTER",
		"BUTTON_TITLE" => "Отправить сообщение",
		"EDIT_ELEMENT" => "N",
		"ELEMENT_ID" => "",
		"ERROR_TEXT" => "",
		"FORM_STYLE" => "WHITE",
		"FORM_TITLE" => "",
		"IBLOCK_ID" => "",
		"IBLOCK_CODE" => "testimonials",
		"IBLOCK_TYPE" => "company",
		"JQUERY_VALID" => "Y",
		"NOT_CREATE_ELEMENT" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"REDIRECT_AFTER_SUCCESS" => "N",
		"SEND_MESSAGE" => "Y",
		"MAIL_EVENT" => "CITRUS_REALTY_NEW_REQUEST",
		"SUB_TEXT" => "",
		"SUCCESS_TEXT" => "Сообщение успешно отправлено",
		"USER_SERVER_VALIDATE" => "N",
		"COMPONENT_TEMPLATE" => "simple",
		"FIELDS" => array(
			"PROPERTY_href" => array(
				"TITLE" => "Отправлено со страницы",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "Y",
				"ORIGINAL_TITLE" => "[54] Отправлено со страницы",
				"DEFAULT" => Citrus\Arealty\Helper::getPath(),
			),
			"PROPERTY_ITEMS" => array(
				"TITLE" => "Объект или услуга",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "Y",
				"ORIGINAL_TITLE" => "Объект или услуга",
				"DEFAULT" => $arParams["ITEM_ID"],
			),
			"group_1493898921502" => array(
				"ORIGINAL_TITLE" => "Новая группа (group_1493898921502)",
				"TITLE" => "",
				"GROUP_FIELD" => "Y",
				"DEPTH_LAVEL" => "1",
				"CLASS" => "row-ib",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "N",
			),
			"group_1493898928264" => array(
				"ORIGINAL_TITLE" => "Новая группа (group_1493898928264)",
				"TITLE" => "",
				"GROUP_FIELD" => "Y",
				"DEPTH_LAVEL" => "2",
				"CLASS" => "col-md-12",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "N",
			),
			"NAME" => array(
				"ORIGINAL_TITLE" => "Название",
				"TITLE" => "Ваше имя",
				"IS_REQUIRED" => "Y",
				"HIDE_FIELD" => "N",
			),
			"group_1493898937831" => array(
				"ORIGINAL_TITLE" => "Новая группа (group_1493898937831)",
				"TITLE" => "",
				"GROUP_FIELD" => "Y",
				"DEPTH_LAVEL" => "2",
				"CLASS" => "col-md-12",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "N",
			),
			"DETAIL_PICTURE" => array(
				"ORIGINAL_TITLE" => "Детальная картинка",
				"TITLE" => "",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "N",
				"TEMPLATE_ID" => "avatar",
				"PLACEHOLDER" => "",
				"DESCRIPTION" => "Вы можете загрузить фото объемом до 10 мб.",
				"VALIDRULE" => "file",
				"ADDITIONAL" => "filetype=.gif, .jpg, .jpeg, .png;filesize=10mb",
			),
			"PREVIEW_TEXT" => array(
				"ORIGINAL_TITLE" => "Описание для анонса",
				"TITLE" => "Ваш отзыв",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "N",
			),
			"ACTIVE" => array(
				"ORIGINAL_TITLE" => "Активность",
				"TITLE" => "Активность",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "Y",
				"DEFAULT" => "N",
			),
			"ACTIVE_FROM" => array(
				"ORIGINAL_TITLE" => "Начало активности",
				"TITLE" => "Начало активности",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "Y",
				"DEFAULT" => ConvertTimeStamp(time(),"SHORT"),
			),
		),
		"SAVE_SESSION" => "Y",
		"FORM_ID" => "68fe236acbcb7d2e4034a68d2fc9bc76",
		"USE_SERVER_VALIDATE" => "N",
		"AJAX" => "Y",
		"USE_GOOGLE_RECAPTCHA" => "N",
		"HIDDEN_ANTI_SPAM" => "Y",
		"AGREEMENT_LINK" => "/agreement/",
		"MAILE_EVENT_TEMPLATE" => array(
		),
		"SEND_IMMEDIATE" => "N",
		"EMAIL_TO_VALUE" => "",
		"EMAIL_SUBJECT" => "",
		"FORM_CLASS" => "",
		"FORM_MOD" => "COMPACT",
		"BUTTON_CLASS" => ""
	),
	false
); ?>
