<?php if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) die();
?>
<? $APPLICATION->IncludeComponent(
	"citrus.forms:iblock.element",
	"simple",
	array(
		"AFTER_FORM_TOOLTIP" => "",
		"AGREEMENT_FIELDS" => "Имя, Email, Телефон",
		"AGREEMENT_LINK" => SITE_DIR . "agreement/",
		"AJAX" => "Y",
		"ANCHOR_ID" => "",
		"BEFORE_FORM_TOOLTIP" => "",
		"BUTTON_CLASS" => "",
		"BUTTON_POSITION" => "JUSTIFY",
		"BUTTON_TITLE" => "Заказать звонок",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"EDIT_ELEMENT" => "N",
		"ELEMENT_ID" => "",
		"EMAIL_SUBJECT" => "Заказ звонка",
		"EMAIL_TO_VALUE" => "",
		"ERROR_TEXT" => "",
		"FIELDS" => array(
			"NAME" => array(
				"ORIGINAL_TITLE" => "Название",
				"TITLE" => "Ваше имя",
				"IS_REQUIRED" => "Y",
				"HIDE_FIELD" => "N",
			),
			"PROPERTY_phone" => array(
				"TITLE" => "Телефон",
				"IS_REQUIRED" => "Y",
				"HIDE_FIELD" => "N",
				"ORIGINAL_TITLE" => "[45] Телефон",
				"TEMPLATE_ID" => "phone",
				"VALIDRULE" => "",
			),
			"PROPERTY_href" => array(
				"TITLE" => "Отправлено со страницы",
				"IS_REQUIRED" => "N",
				"HIDE_FIELD" => "Y",
				"ORIGINAL_TITLE" => "[54] Отправлено со страницы",
				"DEFAULT" => \Citrus\Arealty\Helper::getPath(),
			),
		),
		"FORM_CLASS" => "citrus-form_compact",
		"FORM_ID" => "header_order_call_form",
		"FORM_PLACE_MODE" => "PAGE",
		"FORM_STYLE" => "GRAY",
		"FORM_TITLE" => "",
		"HIDDEN_ANTI_SPAM" => "Y",
		"IBLOCK_CODE" => "order_call",
		"IBLOCK_ID" => "",
		"IBLOCK_TYPE" => "feedback",
		"JQUERY_VALID" => "Y",
		"MAILE_EVENT_TEMPLATE" => array(),
		"MAIL_EVENT" => "CITRUS_REALTY_NEW_REQUEST",
		"NOT_CREATE_ELEMENT" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"REDIRECT_AFTER_SUCCESS" => "N",
		"SAVE_SESSION" => "Y",
		"SEND_IMMEDIATE" => "N",
		"SEND_MESSAGE" => "Y",
		"SUB_TEXT" => "",
		"SUCCESS_TEXT" => "Спасибо! Вам перезвонят в ближайшее время.",
		"USER_CONSENT" => "N",
		"USER_CONSENT_ID" => "1",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "N",
		"USER_SERVER_VALIDATE" => "N",
		"USE_GOOGLE_RECAPTCHA" => "N",
		"USE_SERVER_VALIDATE" => "N",
		"COMPONENT_TEMPLATE" => "simple",
		"FORM_MOD" => "COMPACT",
	),
	$component
); ?>
