<?php
require_once($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_before.php");

if(isset($_REQUEST['id'])){
    if(!is_array($_REQUEST['id'])){ 
        $_REQUEST['id'] = array($_REQUEST['id']);
    }

    $GLOBALS['arrPrintFilter']['ID'] = $_REQUEST['id'];
    
    $APPLICATION->IncludeComponent(
        "bitrix:catalog.section",
        "print_pdf",
        Array(
            "ACTION_VARIABLE" => "action",
            "ADD_PICT_PROP" => "",
            "ADD_PROPERTIES_TO_BASKET" => "N",
            "ADD_SECTIONS_CHAIN" => "N",
            "ADD_TO_BASKET_ACTION" => "ADD",
            "AJAX_MODE" => "N",
            "BACKGROUND_IMAGE" => "",
            "BASKET_URL" => "",
            "PROPERTY_CODE" => array(
                0 => "CITY",
                1 => "NEW_BUILDING",
                2 => "COUNTRY",
                3 => "CITY_AREA",
                4 => "ADDRESS",
                5 => "NEW_ROOMS_AREA",
                6 => "NEW_COMMERCIAL_FEATURES",
                7 => "NEW_COMMERCIAL_TYPE",
                9 => "NEW_FLOOR",
                10 => "NEW_ROOMS_TYPE",
                11 => "DESCRIPTION",
                12 => "contact",
                13 => "deal_type",
                14 => "category",
                15 => "commercial_type",
                16 => "commercial_building_type",
                17 => "deal_status_new",
                18 => "deal_status",
                19 => "deal_status_commercial",
                20 => "rooms",
                21 => "rooms_offered",
                22 => "metro_stations",
                23 => "district",
                24 => "price_for_meter",
                25 => "cost_curr",
                26 => "cost",
                27 => "cost_curr_value",
                28 => "cost_unit",
                29 => "cost_period",
                30 => "agent_fee",
                31 => "prepayment",
                32 => "commercial_rent_conditions",
                33 => "security_payment",
                34 => "apartment",
                35 => "lot_number",
                36 => "cadastral_number",
                37 => "garage_type",
                38 => "taxation_form",
                39 => "common_area",
                40 => "deal_conditions",
                41 => "floors",
                42 => "living_area",
                43 => "rooms_area",
                44 => "kitchen_area",
                45 => "land_area",
                46 => "balcony",
                47 => "share_amount",
                48 => "wc",
                49 => "ownership_type",
                50 => "window_view",
                51 => "renovation",
                52 => "type_of_land",
                53 => "garage_name",
                54 => "condition",
                55 => "walls_type",
                56 => "building_type",
                57 => "building_series",
                58 => "building_section",
                59 => "built_year",
                60 => "ceiling_height",
                61 => "LAND_LORD",
                62 => "entrance_type",
                63 => "BUILDING",
                64 => "phone_lines",
                65 => "rooms_html",
                66 => "RENTAL_COMPANY",
                67 => "garage_features",
                68 => "distance_to_town",
                69 => "garage_building_type",
                70 => "window_type",
                71 => "parking_type",
                72 => "residential_features",
                73 => "building_features",
                74 => "house_features",
                75 => "floor_covering",
                76 => "commercial_purpose",
                77 => "purpose_warehouse",
                78 => "office_class",
                79 => "commercial_building_features",
                80 => "commercial_features",
                81 => "parking_places",
                82 => "parking_place_price",
                83 => "parking_guest_places",
                84 => "geodata",
                85 => "listing_fee",
                86 => "quick_sale",
                87 => "publishterms_sevices",
                88 => "publishterms_excludedsevices",
                89 => "publishterms_ignoreservicepackages",
                91 => "floor",
                92 => "rooms_type",
                93 => "complex",
                94 => "documents",
                95 => "house_type",
                96 => "lift",
            ),
            "BRAND_PROPERTY" => "",
            "BROWSER_TITLE" => "-",
            "CACHE_FILTER" => "N",
            "CACHE_GROUPS" => "Y",
            "CACHE_TIME" => "36000000",
            "CACHE_TYPE" => "N",
            "COMPATIBLE_MODE" => "Y",
            "CONVERT_CURRENCY" => "Y",
            "CURRENCY_ID" => "",
            "CUSTOM_FILTER" => "",
            "DATA_LAYER_NAME" => "",
            "DETAIL_URL" => "",
            "DISABLE_INIT_JS_IN_COMPONENT" => "N",
            "DISCOUNT_PERCENT_POSITION" => "",
            "DISPLAY_BOTTOM_PAGER" => "Y",
            "DISPLAY_TOP_PAGER" => "N",
            "ELEMENT_SORT_FIELD" => "sort",
            "ELEMENT_SORT_FIELD2" => "id",
            "ELEMENT_SORT_ORDER" => "asc",
            "ELEMENT_SORT_ORDER2" => "desc",
            "ENLARGE_PRODUCT" => "PROP",
            "ENLARGE_PROP" => "",
            "FILTER_NAME" => "arrPrintFilter",
            "HIDE_NOT_AVAILABLE" => "N",
            "HIDE_NOT_AVAILABLE_OFFERS" => "N",
            "IBLOCK_ID" => "13",
            "IBLOCK_TYPE" => "arealty",
            "INCLUDE_SUBSECTIONS" => "Y",
            "LAZY_LOAD" => "Y",
            "LINE_ELEMENT_COUNT" => "3",
            "LOAD_ON_SCROLL" => "N",
            "MESSAGE_404" => "",
            "MESS_BTN_ADD_TO_BASKET" => "В корзину",
            "MESS_BTN_BUY" => "Купить",
            "MESS_BTN_DETAIL" => "Подробнее",
            "MESS_BTN_LAZY_LOAD" => "Показать ещё",
            "MESS_BTN_SUBSCRIBE" => "Подписаться",
            "MESS_NOT_AVAILABLE" => "Нет в наличии",
            "META_DESCRIPTION" => "-",
            "META_KEYWORDS" => "-",
            "PAGER_BASE_LINK_ENABLE" => "N",
            "PAGER_DESC_NUMBERING" => "N",
            "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
            "PAGER_SHOW_ALL" => "N",
            "PAGER_SHOW_ALWAYS" => "N",
            "PAGER_TEMPLATE" => ".default",
            "PAGER_TITLE" => "Товары",
            "PARTIAL_PRODUCT_PROPERTIES" => "N",
            "PRICE_CODE" => array("BASE"),
            "PRICE_VAT_INCLUDE" => "Y",
            "PROPERTY_CODE" => array("NEWPRODUCT",""),
            "PROPERTY_CODE_MOBILE" => array(),
            "SECTION_CODE" => "",
            "SECTION_ID" => "",
            "SEF_MODE" => "Y",
            "SET_BROWSER_TITLE" => "N",
            "SET_LAST_MODIFIED" => "N",
            "SET_META_DESCRIPTION" => "N",
            "SET_META_KEYWORDS" => "N",
            "SET_STATUS_404" => "N",
            "SET_TITLE" => "N",
            "SHOW_404" => "N",
            "SHOW_ALL_WO_SECTION" => "Y",
            "SHOW_CLOSE_POPUP" => "N",
            "SHOW_DISCOUNT_PERCENT" => "N",
            "SHOW_FROM_SECTION" => "N",
            "SHOW_MAX_QUANTITY" => "N",
            "SHOW_OLD_PRICE" => "N",
            "SHOW_PRICE_COUNT" => "1",
            "TEMPLATE_THEME" => "",
            "USE_ENHANCED_ECOMMERCE" => "N",
            "USE_MAIN_ELEMENT_SECTION" => "N",
            "USE_PRICE_COUNT" => "N",
            "USE_PRODUCT_QUANTITY" => "N"
        )
    );
}else {
    echo 'Отсутствуют элементы для печати';
}

require_once($_SERVER["DOCUMENT_ROOT"]."/bitrix/modules/main/include/prolog_after.php");