<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("SHOW_TITLE", "Y");
$APPLICATION->SetPageProperty("description", "Сайт агентства недвижимости. Предложения");
$APPLICATION->SetTitle("Предложения");

?><?$APPLICATION->IncludeComponent(
	"citrus:realty.catalog",
	"",
	Array(
		"ACTION_VARIABLE" => "action",
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_PICT_PROP" => "-",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "Y",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BASKET_URL" => "/personal/basket.php",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CURRENCY" => \Citrus\Arealty\Helper::getSelectedCurrency(),
		"DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
		"DETAIL_BRAND_USE" => "N",
		"DETAIL_BROWSER_TITLE" => "-",
		"DETAIL_DETAIL_PICTURE_MODE" => "IMG",
		"DETAIL_DISPLAY_NAME" => "Y",
		"DETAIL_DISPLAY_NUMBER" => "N",
		"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
		"DETAIL_META_DESCRIPTION" => "-",
		"DETAIL_META_KEYWORDS" => "-",
		"DETAIL_PROPERTY_CODE" => array("contact","deal_type","category","commercial_type","commercial_building_type","rooms","rooms_offered","metro_stations","district","cost","garage_type","common_area","floor","floors","living_area","rooms_area","kitchen_area","land_area","balcony","wc","rooms_type","window_view","renovation","type_of_land","condition","walls_type","building_type","building_section","built_year","ceiling_height","entrance_type","phone_lines","garage_features","distance_to_town","garage_building_type","window_type","parking_type","house_features","floor_covering","commercial_purpose","purpose_warehouse","office_class","parking_places","complex","documents","house_type","lift",""),
		"DETAIL_SET_CANONICAL_URL" => "Y",
		"DETAIL_SHOW_SIMILAR_OFFERS" => "Y",
		"DETAIL_USE_COMMENTS" => "N",
		"DETAIL_USE_VOTE_RATING" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD2" => "shows",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER2" => "desc",
		"EMPTY_LIST_MESSAGE" => "",
		"FILE_404" => "/404.php",
		"FILTER_FIELD_CODE" => array(0=>"",1=>"",),
		"FILTER_NAME" => "arrFilter",
		"FILTER_PRICE_CODE" => array(0=>"cost",),
		"FILTER_PROPERTY_CODE" => array(0=>"rooms",1=>"district",2=>"common_area",3=>"balcony",4=>"wc",5=>"house_type",6=>"complex",7=>"commercial_features",8=>"rooms_area",),
		"FILTER_VIEW_MODE" => "VERTICAL",
		"IBLOCK_ID" => "13",
		"IBLOCK_TYPE" => "realty",
		"INCLUDE_SUBSECTIONS" => "Y",
		"LABEL_PROP" => "-",
		"LINE_ELEMENT_COUNT" => "1",
		"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
		"LINK_IBLOCK_ID" => "3",
		"LINK_IBLOCK_TYPE" => "company",
		"LINK_PROPERTY_SID" => "",
		"LIST_BROWSER_TITLE" => "-",
		"LIST_META_DESCRIPTION" => "-",
		"LIST_META_KEYWORDS" => "-",
		"LIST_PROPERTY_CODE" => array("district","cost","rooms_area","commercial_features",""),
		"MESS_BTN_ADD_TO_BASKET" => "В корзину",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_COMPARE" => "Сравнение",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_NOT_AVAILABLE" => "Нет в наличии",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "",
		"PAGER_TITLE" => "Предложения",
		"PAGE_ELEMENT_COUNT" => "15",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"PRICE_CODE" => array(0=>"cost",),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_PROPERTIES" => "",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PROP_LINK" => array("commercial_type","rooms_area","commercial_features",""),
		"REDIRECT_TO_SECTION_404" => "N",
		"SECTIONS_HIDE_SECTION_NAME" => "N",
		"SECTIONS_SHOW_PARENT_NAME" => "N",
		"SECTIONS_VIEW_MODE" => "LIST",
		"SECTION_COUNT_ELEMENTS" => "Y",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_TOP_DEPTH" => "2",
		"SEF_FOLDER" => "/predlozhenija/",
		"SEF_MODE" => "Y",
		"SEF_URL_TEMPLATES" => Array(
			"element"=>"#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
			"favourites"=>"izbrannoe/",
			"pdf"=>"pdf/",
			"print"=>"print/",
			"section"=>"#SECTION_CODE_PATH#/",
			"sections"=>"",
			"smart_filter"=>""),
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "N",
		"SHARE_SERVICES" => array("mailru","facebook","twitter","lj","delicious","vk"),
		"SHOW_404" => "Y",
		"SHOW_PRICE_COUNT" => "1",
		"SHOW_TOP_ELEMENTS" => "N",
		"TEMPLATE_THEME" => CModule::IncludeModule("citrus.arealty")?\Citrus\Arealty\Helper::getTheme():"",
		"TOP_ELEMENT_COUNT" => "9",
		"TOP_ELEMENT_SORT_FIELD" => "shows",
		"TOP_ELEMENT_SORT_FIELD2" => "id",
		"TOP_ELEMENT_SORT_ORDER" => "desc",
		"TOP_ELEMENT_SORT_ORDER2" => "asc",
		"TOP_LINE_ELEMENT_COUNT" => "2",
		"TOP_PROPERTY_CODE" => array(0=>"rooms",1=>"",),
		"TOP_ROTATE_TIMER" => "30",
		"TOP_VIEW_MODE" => "BANNER",
		"USE_COMPARE" => "N",
		"USE_ELEMENT_COUNTER" => "Y",
		"USE_FILTER" => "Y",
		"USE_PRICE_COUNT" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"USE_REVIEW" => "N",
		"USE_STORE" => "N"
	)
);?><br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>